# Funding platforms
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [taro33333]
# ko_fi: # Replace with your Ko-fi username
# patreon: # Replace with your Patreon username
# custom: ['https://www.buymeacoffee.com/yourusername']

